//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseTaskDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BaseTaskDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToStationField;
        
        private int PriorityField;
        
        private System.DateTime CreateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FromStation {
            get {
                return this.FromStationField;
            }
            set {
                if ((object.ReferenceEquals(this.FromStationField, value) != true)) {
                    this.FromStationField = value;
                    this.RaisePropertyChanged("FromStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ToStation {
            get {
                return this.ToStationField;
            }
            set {
                if ((object.ReferenceEquals(this.ToStationField, value) != true)) {
                    this.ToStationField = value;
                    this.RaisePropertyChanged("ToStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name NonExecuateTaskResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NonExecuateTask", ReplyAction="*")]
        WebTest.ServiceReference1.NonExecuateTaskResponse NonExecuateTask(WebTest.ServiceReference1.NonExecuateTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NonExecuateTask", ReplyAction="*")]
        System.Threading.Tasks.Task<WebTest.ServiceReference1.NonExecuateTaskResponse> NonExecuateTaskAsync(WebTest.ServiceReference1.NonExecuateTaskRequest request);
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebTest.ServiceReference1.HelloWorldResponse HelloWorld(WebTest.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebTest.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WebTest.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int a, int b);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NonExecuateTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NonExecuateTask", Namespace="http://tempuri.org/", Order=0)]
        public WebTest.ServiceReference1.NonExecuateTaskRequestBody Body;
        
        public NonExecuateTaskRequest() {
        }
        
        public NonExecuateTaskRequest(WebTest.ServiceReference1.NonExecuateTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class NonExecuateTaskRequestBody {
        
        public NonExecuateTaskRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NonExecuateTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NonExecuateTaskResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebTest.ServiceReference1.NonExecuateTaskResponseBody Body;
        
        public NonExecuateTaskResponse() {
        }
        
        public NonExecuateTaskResponse(WebTest.ServiceReference1.NonExecuateTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NonExecuateTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebTest.ServiceReference1.BaseTaskDTO[] NonExecuateTaskResult;
        
        public NonExecuateTaskResponseBody() {
        }
        
        public NonExecuateTaskResponseBody(WebTest.ServiceReference1.BaseTaskDTO[] NonExecuateTaskResult) {
            this.NonExecuateTaskResult = NonExecuateTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebTest.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebTest.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebTest.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebTest.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebTest.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebTest.ServiceReference1.WebService1Soap>, WebTest.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebTest.ServiceReference1.NonExecuateTaskResponse WebTest.ServiceReference1.WebService1Soap.NonExecuateTask(WebTest.ServiceReference1.NonExecuateTaskRequest request) {
            return base.Channel.NonExecuateTask(request);
        }
        
        public WebTest.ServiceReference1.BaseTaskDTO[] NonExecuateTask() {
            WebTest.ServiceReference1.NonExecuateTaskRequest inValue = new WebTest.ServiceReference1.NonExecuateTaskRequest();
            inValue.Body = new WebTest.ServiceReference1.NonExecuateTaskRequestBody();
            WebTest.ServiceReference1.NonExecuateTaskResponse retVal = ((WebTest.ServiceReference1.WebService1Soap)(this)).NonExecuateTask(inValue);
            return retVal.Body.NonExecuateTaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebTest.ServiceReference1.NonExecuateTaskResponse> WebTest.ServiceReference1.WebService1Soap.NonExecuateTaskAsync(WebTest.ServiceReference1.NonExecuateTaskRequest request) {
            return base.Channel.NonExecuateTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebTest.ServiceReference1.NonExecuateTaskResponse> NonExecuateTaskAsync() {
            WebTest.ServiceReference1.NonExecuateTaskRequest inValue = new WebTest.ServiceReference1.NonExecuateTaskRequest();
            inValue.Body = new WebTest.ServiceReference1.NonExecuateTaskRequestBody();
            return ((WebTest.ServiceReference1.WebService1Soap)(this)).NonExecuateTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebTest.ServiceReference1.HelloWorldResponse WebTest.ServiceReference1.WebService1Soap.HelloWorld(WebTest.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebTest.ServiceReference1.HelloWorldRequest inValue = new WebTest.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebTest.ServiceReference1.HelloWorldRequestBody();
            WebTest.ServiceReference1.HelloWorldResponse retVal = ((WebTest.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebTest.ServiceReference1.HelloWorldResponse> WebTest.ServiceReference1.WebService1Soap.HelloWorldAsync(WebTest.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebTest.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WebTest.ServiceReference1.HelloWorldRequest inValue = new WebTest.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebTest.ServiceReference1.HelloWorldRequestBody();
            return ((WebTest.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int a, int b) {
            return base.Channel.AddAsync(a, b);
        }
    }
}
